site_name: Starlight Engine
repo_url: https://github.com/j-eriksmith/starlight-engine
edit_uri: null
nav:
  - Intro to Starlight: intro.md
  - Math: math.md
  - Memory Manager: memory.md
  - File I/O + Resource Manager: fileio.md
  - Graphics: graphics.md
  - Entity Component System: ecs.md
  - Collision Detection: collision.md
  - Input: input.md
  - Audio: audio.md
  - Conclusions: conclusions.md
theme: readthedocs
